### ISSUE TITLE
Commands and Functionality

### ISSUE THREAD

**Issue by AndreasLc1103** [AndreasLc1103/MaxwellBot#2]
The specific key of commands and added functionality to Maxwell
- [ ] User info
- [ ] Name
- [x] Undeafan
- [x] Mute user
- [x] Unmute user
- [ ] Mute server
- [ ] Deafen server
- [x] Kick
- [ ] Ban
- [ ] Stop
- [ ] Pause
- [x] Redirect to Powerschool
- [ ] Play

**Comment by Djboy08** [comment]
Project let go.
